name: flutter_training
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1
  flutter: ^3.24.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  pedantic_mono: ^1.21.1

flutter:
  uses-material-design: true

  assets:
    - assets/sunny.svg
    - assets/rainy.svg
    - assets/cloudy.svg
